### ISSUE TITLE
Add an example where the host reads & writes local scratchpads

### ISSUE THREAD

**Issue by sampsyo** [cucapra/hb-examples#2]
All the examples so far use the malloc-and-memcpy approach, which allocates inputs & outputs in the device DRAM. It would also be interesting to show how to read & write directly into statically allocated buffers in tile SRAMs.

The key primitive might be using [`hb_mc_manycore_eva_write`](https://github.com/bespoke-silicon-group/bsg_f1/blob/2f9fc8460f8566e70b6a616647696eba93da6e8e/cl_manycore/libraries/bsg_manycore_eva.cpp#L806-L810) and `..._read` directly, which are what the memcpy function uses under the hood. That will need to work with `hb_mc_loader_symbol_to_eva` to look up the symbol for the statically allocated buffer.

**Comment by avanhatt** [comment]
Note that `dram-read-write` added in 8da91ea2dc1919b680dcf7ba8d5f03234214251e shows writing to statically allocated device DRAM with `hb_mc_manycore_eva_write` and `hb_mc_loader_symbol_to_eva`. Adding another example that writes into individual tiles' SRAM next.
