### ISSUE TITLE
Figure out how many tiles are actually safe to use on F1

### ISSUE THREAD

**Issue by sampsyo** [cucapra/hb-examples#4]
I kinda thought it would be possible to use a 4x3 grid of tiles (that's what the old example did!), but so far I haven't gotten anything more than 2x2 to work. Let's do some experiments and ask the developers to see what we can learn about what's going on here. (Someday, maybe we can even use all 4x4!)

**Comment by avanhatt** [comment]
4x4 now works on v3.0.6!
